version: "3"

services:
  database:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.database
    container_name: mpc-db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/app
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
