version: "3"

services:
  application:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.application
    container_name: mpc-application
    depends_on:
      - rest-api
    ports:
      - "8081:8081"
    volumes:
      - ./application:/app

  database:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.database
    container_name: mpc-db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/app
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  rest-api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.rest-api
    container_name: mpc-rest-api
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - ./rest-api:/app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
